Add permissions in the in-cluster RBAC doc
digitalocean/clusterlint pull request #154
Opened 2022-11-21 17:33 UTC by tnorris

Clusterlint is rad, while trying to deploy it at work, I ran into API permission errors. Someone else might be trying to do this, so here's a docfix 😄 

This patch does three things:
- Add missing permissions for what seems like newer checks and API Groups
- Sorts the list of permissions
- Changes the RoleBinding to a ClusterRoleBinding so permissions can be picked up by the ServiceAccount

2022-12-08 20:46 UTC, tnorris commented
Hi @sundowndev, sorry for the ping, but you're someone that touched the RBAC docs. Do you mind taking a look at this? 😃

2022-12-09 11:42 UTC, sundowndev requested changes
Thanks for your PR @tnorris 🙏🏻 

I left few comments

2022-12-09 11:42 UTC, sundowndev commented on docs/RBAC.md
> +   - volumesnapshots
I think we can remove `volumesnapshots` here since it's covered below

2022-12-09 11:46 UTC, sundowndev commented on docs/RBAC.md
>    namespace: clusterlint
Since it's now cluster-scoped, you need to remove the namespace here

2022-12-12 05:04 UTC, sundowndev approved these changes
LGTM - I'll let the core team review and merge now

cc @varshavaradarajan @adamwg

2022-12-12 16:16 UTC, adamwg reviewed
One small yaml issue, otherwise this looks good to me.

2022-12-12 16:16 UTC, adamwg commented on docs/RBAC.md
> +- apiGroups: ["snapshot.storage.k8s.io"]]
Looks like an extra `]` at the end of this line.

2022-12-15 17:36 UTC, varshavaradarajan approved these changes

2022-12-15 17:37 UTC, merged

2022-12-15 17:37 UTC, varshavaradarajan commented
Thank you @tnorris and @sundowndev!